algoritmo "exemplo3"
// Disciplina   : [Algoritmos]
// Descrição   : Estrutura de repetição com variável de controle
// Autor(a)    : Leonir Kochenborger
// Data : 12/02/2025
var
// Seção de declarações das variáveis
   m: inteiro

inicio
// Seção de comandos, procedimento, funções, operadores, etc...
      para m de 0 ate 100 passo 20 faca
           se (m <> 0) entao
              escreval("Múltiplo de 20 = ", m)
           fimse
      fimpara

fimalgoritmo
