Algoritmo "exemplo1"
// Disciplina   : [Algoritmos]
// Descrição   : Calcular a média aritmética entre duas notas
// Autor(a)    : Leonir Kochenborger
// Data atual  : 03/02/2025
Var
// Seção de Declarações das variáveis 
 nota1, nota2, media: real

Inicio
// Seção de comandos, procedimento, funções, operadores, etc...
 escreval ("Digite a primeira nota")
 leia (nota1)
 escreval ("Digite a segunda nota")
 leia (nota2)
 media <- (nota1 + nota2) /2
 escreval ("Média =", media)

Fimalgoritmo
