algoritmo "exemplo5"
// Disciplina   : [Algoritmos]
// Descrição   : Estrutura de repetição com variável de controle
// Autor(a)    : Leonir Kochenborger
// Data : 12/02/2025
var
// Seção de declarações das variáveis
   i: inteiro

inicio
// Seção de comandos, procedimento, funções, operadores, etc...
   i <- 0
   
   enquanto (i <= 5) faca
       escreval("Estudar")
       
       i <- i + 1
   fimenquanto
   
fimalgoritmo
