algoritmo "exemplo2"
// Disciplina   : [Algoritmos]
// Descrição   : Estrutura de repetição com variável de controle
// Autor(a)    : Leonir Kochenborger
// Data : 12/02/2025
var
   x: inteiro
// Seção de declarações das variáveis

inicio
      para x de 5 ate 1 passo -1 faca
           escreval("Valor de x= ", x)
      fimpara

// Seção de comandos, procedimento, funções, operadores, etc...
fimalgoritmo
