algoritmo "exemplo4"
// Disciplina   : [Algoritmos]
// Descrição   : Estrutura de repetição com variável de controle
// Autor(a)    : Leonir Kochenborger
// Data : 12/02/2025
var
// Seção de declarações das variáveis
   m: inteiro

inicio
// Seção de comandos, procedimento, funções, operadores, etc...
   escreval("Números de 250 a 25")
   para m de 250 ate 25 passo -25 faca
        escreval("Número = ", m)
   fimpara

fimalgoritmo
