algoritmo "exemplo8"
// Disciplina   : [Algoritmos]
// Descrição   : Estrutura de repetição condicional com teste no final
// Autor(a)    : Leonir Kochenborger
// Data : 12/02/2025
var
// Seção de declarações das variáveis
   i: inteiro

inicio
// Seção de comandos, procedimento, funções, operadores, etc...
   i <- 1
   repita
       escreval("valor de i = ", i)
       i <- i + 1
   ate i > 5

fimalgoritmo
