algoritmo "exemplo7"
// Disciplina   : [Algoritmos]
// Descrição   : Estrutura de repetição condicional com teste no final
// Autor(a)    : Leonir Kochenborger
// Data : 12/02/2025
var
// Seção de declarações das variáveis
   i: inteiro

inicio
// Seção de comandos, procedimento, funções, operadores, etc...
   i <- 10
   repita
       escreval("valor de i = ", i)
       i <- i + 10
   ate i > 50

fimalgoritmo
